import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#050816] text-white`}>
        <Box component="main">
          <Toolbar />
          {children}
        </Box>
      </body>
    </html>
  );
}
